version: '3'
services:
  board-api:
    build: .
    command: ["go", "run", "."]
    volumes:
      - .:/go/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASS: 1234
    ports:
      - 5432:5432
